### ISSUE TITLE
Broken layout on iOS for pot info

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/pokemon-sleep-ui#1090]
![Image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/aff44895-d80a-418b-a193-9f7fa34ea06f)

**Comment by johnmgrant** [comment]
What screen is this?

**Comment by RaenonX** [comment]
> What screen is this? It looks like the recipe prepare screen, but it's looking fine on my device.

Seems like https://pks.raenonx.cc/en/info/pot
Looks fine on my devices and seems iOS specific (again)

**Comment by johnmgrant** [comment]
> ...
> Seems like https://pks.raenonx.cc/en/info/pot
> 
> Looks fine on my devices and seems iOS specific (again)

ok, thanks. I was able to replicate. I'll take a look.

**Comment by RaenonX** [comment]
Seems like there is some weird bug when `grid` has a nested `flex`. This only happens on Safari.
