### ISSUE TITLE
Possibly incorrect shiny boost timing in Pokemon page

### ISSUE THREAD

**Issue by psp0** [RaenonX-PokemonSleep/pokemon-sleep-ui#1093]
1. Problem
DB errors containing abnormal values ​​such as 1970-01-01 00:00 or 2100-01-01 00:00, or Initial value setting code errors about connection between Pokemon and events.

2. How bugs occur
The bugs can be observed by checking the event information of several Pokémon in the Pokédex.

3. Expected Outcome
The time might be corrected properly.

4. Screenshot

- In case of [이상해씨](https://pks.raenonx.cc/en/pokedex/1)
![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/76198219/083c62af-d862-462a-9a3c-7ee020e020b7)

- In case of [라이코](https://pks.raenonx.cc/en/pokedex/243)
![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/76198219/e5f966f4-ba9d-4303-9cf7-a655e070a144)

**Comment by RaenonX** [comment]
Can't tell if this is a bug tho, because these came from datamine, and it is possible that we did really have these shiny boost history before.

Raikou does have "permanent" shiny boost per the data.

Personally I would leave them as-is, because they're whatever really in the DB.

**Comment by psp0** [comment]
Ah, there was a reason for that. If there is no related explanation, it may be misunderstood.😅

**Comment by RaenonX** [comment]
> Ah, there was a reason for that! If there is no related explanation, it may be misunderstood.😅

Agree with this, but I don't know how to explain tbh, because apparently all our info are from datamine (including this), and this does look weird but it is what it is
