### ISSUE TITLE
Cooking to add considerations of filler ingredients

### ISSUE THREAD

**Issue by robertpainsi** [RaenonX-PokemonSleep/pokemon-sleep-ui#147]
https://pks.raenonx.cc/en/cooking

- A  _Hearty Cheeseburger Curry_ at level 1 uses 8 _Moomoo Milk_, and 8 _Bean Sausage_ and gives a final strength of _1785_ including a bonus strentgh of (+_177_ / +_11_%)
- A _Simple Chowder_ at level 18 uses 7 _Moomoo Milk_ and gives a final strength of _952_ including a bonus strength of (+_266_ / +_39_%)

Since the _Hearty Cheeseburger Curry_ gives a higher final strength, it's ranked higher (ordered first). However, using 8 _Moomoo Milk_ and 8 _Bean Sausage_ to prepare a _Simple Chowder_ will give you a total strength of _1874_ (`8 * 98 + 8 * 103 + 266`). Therefore, it's better to prepare meals with higher bonuses and use as many ingredients as possible instead.

So meals should either be
- ordered by bonus by default
- or there should be an option to order meals by bonuses.

I have to admit that I haven't tested how the game determines which meal to cook. If I click on a recipe and add more ingredients, will the meal also automatically change?

~- If yes, this ticket can be closed~ (please see [comment](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/issues/147#issuecomment-1693302832))
- If no, please improve the order of meals

**Comment by robertpainsi** [comment]
Rereading the issue, I think it's still useful even if the recipe is detected automatically. You just put as many ingredients into the pot without changing the meal by either using a total of 7 _Moomoo Milk_ or 7 _Bean Sausage_ and use other ingredients instead.

When cooking with a full pot, the meal with the higher bonus is the preferred one (in general).

**Comment by RaenonX** [comment]
> I have to admit that I haven't tested how the game determines which meal to cook. If I click on a recipe and add more ingredients, will the meal also automatically change?

No for now, there's no option for manually adding ingredients, yet. I would say it might be better if the tool can automatically calculates what you should add and sort based on what you have, since it's already an input.

I would avoid simply sort by bonus because if there's an edge case that you got +39% and +11% where +11% takes way more ingredients (maybe 40?) and +39% takes tiny amount of ingredients (8?), then +11% one might still outperform the +39% one because `39% * (8 / 40)` is `7.8%` which is <11%.

I have added this feature request to the queue, but I would say if this is implemented, I'll make a toggle of `auto-fill` because sometimes you would want to save certain ingredients for a better meal instead.

Let me know if this sounds like a plan to you.

----------------------

Regarding the implmentation status - if you're ever curious, you can check "Project." to get an idea.

**Comment by robertpainsi** [comment]
> I would avoid simply sort by bonus because if there's an edge case that you got +39% and +11% where +11% takes way more ingredients (maybe 40?) and +39% takes tiny amount of ingredients (8?), then +11% one might still outperform the +39% one because `39% * (8 / 40)` is `7.8%` which is <11%.

I get your point!

<details>
<summary>Click to expand! Feel free to read this! :smile:</summary>

Hmm… In your example, to me it looks like that both ordering types (by final strength or by bonus) both have their own advantages/drawbacks. It always depends on what ingredients you have and if you favor final strength or the bonus.

You already did some Math and also may already knew all of this. If so, just see it as documentation :wink:

e.g. if you have 40 _Greengrass Soybeans_ (100 strength each) you'll get a 
- total strength of **4440** if you cook the 11% meal
- total strength of 4312 if you cook the 39% meal

So you get 128 strength more/for free if you cook the 11% meal.

However, if you strive to get the highest strength, you would use 8 _Greengrass Soybeans_ (100 strength each) and 32 _Slowpoke Tail_ (342 strength each) for the 39% meal :arrow_right:

- total strength of **12056** if you cook the 39% meal

The bonus/free strength points you get is still lower, however the total strength is 7616 higher.

In the end in your example it depends so much on what other ingredients you have and want to use…

However, I experienced following example I'm referring to just today (as mentioned above):
![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/1794599/4518dea7-cb1a-4de7-90ba-4fabbe193bdc)

Either way, the _Simple Chowder_ is the better option. It gives you a higher bonus *and* if you use the same 16 ingredients in both cases, a higher total strength (**~1875**).

Just to clarify, I'm not saying that my case is the common one, just now we have two different cases (and there may be even more).

</details>

Uff, I just wrote all of this just to find out to also consider the level (leveling up). For sure the _Simple Chowder_ is the better option. However, leveling up the _Hearty Cheeseburger Curry_ to level 4 and you already get a bigger bonus. Some of the info mentioned above still is true. However, it makes the whole thing so much more complicated…

It's a tough choice for sure imo. It's completely up to you how to handle it. Maybe drop it completely and concentrate on features that are more important! Can't wait to see the _Team Building Help_ feature getting released :wink: Thanks for reading! :bow: 

> Regarding the implmentation status - if you're ever curious, you can check "Project." to get an idea.

ty! :bow:

**Comment by RaenonX** [comment]
Just expanded your doc - and that was almost my thought process when I was focusing on the cooking page.
And you got about the same as my conslusion too - cooking the lower-end one seems to be a better option for now, but what about in the future?
I even came up an idea of making a meal schedule, but figured it's gonna be an infinite loop lol

For this one, I think I'll make it a toggle to see if the user wants to include auto-full, and if so, the cooking page would just pick the fillers and output the results - or let the users to pick it.

I'll think about this more when I shift my focus back here :)

**Comment by RaenonX** [comment]
Since the ultimate goal of this discussion was to figure out how to better address ingredient bonus and the formula of the dish output is clear now, #364 should help addressing this better.
