### ISSUE TITLE
技能部分的帮忙速度缩减存在35%的上限的隐藏设定

### ISSUE THREAD

**Issue by pmsleepcheck** [RaenonX-PokemonSleep/pokemon-sleep-ui#354]
サブスキルによるおてつだい時間短縮の上限について：
サブスキルによるおてつだい時間短縮(現状実装されているもの：'おてつだいボーナス'、'おてつだいスピードS'、'おてつだいスピードM')の効果の合計は各ポケモン 上限35% となります。
根据官方公告，副技能部分的帮忙速度缩减存在一个35%的上限。按字面应该不包括性格。 
![-9oxvQjys-d89xZeT3cStn-e5](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/142955583/ae0386a2-abe2-45cb-b3d6-c881305abe12)

**Comment by RaenonX** [comment]
這部分已經做了

https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/15d0982ad2334089d199a4b1829db85d8470e6cf/src/utils/game/producing/frequency.ts#L31

**Comment by pmsleepcheck** [comment]
目前来说評級如果忽略0.35的上限 会导致帮助m被严重高估 
极端情况下帮助奖励+帮忙m+帮忙s被多算了30%的收益

**Comment by RaenonX** [comment]
> 目前来说評級如果忽略0.35的上限 会导致帮助m被严重高估 极端情况下帮助奖励+帮忙m+帮忙s被多算了30%的收益

我不太確定我是不是有理解你說的

你提的這個例子在實際遊戲中是 幫手獎勵 -5%、幫忙M -14%、幫忙S -7%，這三個疊起來是 `5+14+7 = 26`，連上限都還沒碰到才對？

評級是為了讓總能量貼近實際情況才把原本 -5% 的效果當作 -25% 計算，實際遊戲中對單一隻寶可夢的效果並不是真的 -25%

**Comment by pmsleepcheck** [comment]
幫手獎勵是全队可以叠加生效的（否则这个公告就没有意义），
