### ISSUE TITLE
iOS users reporting Team Analysis slowness

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/pokemon-sleep-ui#429]
## Potential improvements

- #532 could help as it reduces DOM node count.
- #592 could help reducing DOM node count as well as cutting down image loads

## Notes

- `bg-blink` might not be the actual issue here.
  - `bg-blink` usage removed in #425
  - After removal, Discord @ babidehh is reporting only getting slightly better / [video](https://cdn.discordapp.com/attachments/1138701820273885196/1170029121053671424/RPReplay_Final1699027055.mov)
- [Discord channel (CH)](https://discord.com/channels/1138701819464392744/1169833799958397039) reported only team analysis is slow, started around 2 weeks ago, might be because of webpack according to lighthouse?
- This might be related to #404 as well, because the body size was the height of the screen, but now the whole content page

**Comment by RaenonX** [comment]
It was reported that iPhone 12 with iOS 15.6 is working completely fine in Team Analysis, but but iPhone 12 with iOS 16.6 is not.

**Comment by RaenonX** [comment]
The lagging issue also might have something to do with rendering whatever is available on the screen

**Comment by RaenonX** [comment]
Magically resolved itself.

**Comment by RaenonX** [comment]
https://drive.google.com/drive/folders/19xBu-8-01Gyi7EGxmB05UDpqJ5tuIh7B?usp=drive_link

**Comment by johnmgrant** [comment]
@RaenonX Created a script for logging to `rerender` calls I was noticing. None during scroll, but the calls multiply with each selection.

Script can be found [here](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/pull/608) and attaching [log](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/files/13707192/team_analysis_iOS-17.log) as well.

**Comment by RaenonX** [comment]
> @RaenonX Created a script for logging to `rerender` calls I was noticing. None during scroll, but the calls multiply with each selection.
> 
> Script can be found [here](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/pull/608) and attaching [log](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/files/13707192/team_analysis_iOS-17.log) as well.

Is the log after L125 all spits out at once? That kinda explains why users are experiencing lags, although I am not sure where it rerenders so many times yet

**Comment by johnmgrant** [comment]
> > @RaenonX Created a script for logging to `rerender` calls I was noticing. None during scroll, but the calls multiply with each selection.
> > Script can be found [here](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/pull/608) and attaching [log](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/files/13707192/team_analysis_iOS-17.log) as well.
> 
> Is the log after L125 all spits out at once? That kinda explains why users are experiencing lags, although I am not sure where it rerenders so many times yet

Yes, and the webpage took about 25 seconds to rerender the full team analysis view.

**Comment by RaenonX** [comment]
@johnmgrant By selection Pokemon, did you select it from the top, or Pokebox importer?

**Comment by johnmgrant** [comment]
> @johnmgrant By selection Pokemon, did you select it from the top, or Pokebox importer?

Selected from the pokebox. See reference in script [here](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/d4abd02c1f498c598344d37747efe4ef5bc136a2/scripts/team-analysis-logger.js#L27-L44).

**Comment by RaenonX** [comment]
> > @johnmgrant By selection Pokemon, did you select it from the top, or Pokebox importer?
> 
> Selected from the pokebox. See reference in script [here](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/d4abd02c1f498c598344d37747efe4ef5bc136a2/scripts/team-analysis-logger.js#L27-L44).

Ah OK, then it's from the importer. I'll check further.
