### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/pokemon-sleep-ui#633]
Workaround for #429.

**Comment by johnmgrant** [comment]
To be clear, #632 doesn't _fix_ #429.. It's a workaround to allowing iOS to treat the site as a standalone *Safari App.. It seems that the site has a bit more wiggle room in terms of memory, but I'd ultimately like to continue looking into what more I can track down as to the underlying issue as apart of #625.

**Comment by RaenonX** [comment]
> To be clear, #632 doesn't _fix_ #429.. It's a workaround to allowing iOS to treat the site as a standalone *Safari App.. It seems that the site has a bit more wiggle room in terms of memory, but I'd ultimately like to continue looking into what more I can track down as to the underlying issue as apart of #625.

Oh OK, I'll modify the first content

**Comment by johnmgrant** [comment]
Screen recording of the performance improvement for the PWA on iOS 15.5 iPhone 11 Pro simulation.

https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/10672193/58fedf14-73f6-4b8e-9c2d-42bff0e2f43d
