### ISSUE TITLE
Tier list light mode incorrect button shadowing

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/pokemon-sleep-ui#696]
![Image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/c16e312e-24b8-4896-aa56-7613f6e0dd28)

**Comment by wakashio** [comment]
@RaenonX 
Is this the way it should look?
https://www.awesomescreenshot.com/video/24533565?key=7ca7e8517b051f3246f63f99b7304054

**Comment by wakashio** [comment]
Here's how it is now.
https://www.awesomescreenshot.com/video/24533667?key=1e150e48c2daf384364cbabce284b93a

**Comment by RaenonX** [comment]
> @RaenonX Is this the way it should look? https://www.awesomescreenshot.com/video/24533565?key=7ca7e8517b051f3246f63f99b7304054

Not really, check what the button looks like in here I light mode, that's how it should look like (have a slight black surrounding the button) https://pks.raenonx.cc/en/ingredient/3

Currently it's only showing around the corner, which is unexpected

**Comment by wakashio** [comment]
@RaenonX 
I see, I thought it should be the same as the design of this page.
https://pks.raenonx.cc/en/pokedex

Now that I know the difference, let's take a closer look.

**Comment by RaenonX** [comment]
> @RaenonX I see, I thought it should be the same as the design of this page. https://pks.raenonx.cc/en/pokedex
> 
> Now that I know the difference, let's take a closer look.

Actually good catch, buttons there should have that shading as well. I'll open a ticket and assign it to you, you can name the branch like `dev/button-shadowing` or `dev/696-(ticket number)` for this.

**Comment by wakashio** [comment]
@RaenonX 
Thank you very much.
I also understand the branch naming convention.

By the way, I have identified the cause of this happening.
It seems that the shadow cast by the FlexButton is being hidden by the AnimatedCollapse div.

Giving padding to the AnimatedCollapse with p-1 will make the shadow appear, although the design will be a little different...

like this
![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/49340378/88d2de41-1a25-4548-a0ef-4e9af1efd7b7)

**Comment by RaenonX** [comment]
> @RaenonX Thank you very much. I also understand the branch naming convention.
> 
> By the way, I have identified the cause of this happening. It seems that the shadow cast by the FlexButton is being hidden by the AnimatedCollapse div.
> 
> Giving padding to the AnimatedCollapse with `p-1` will make the shadow appear, although the design will be a little different...
> 
> like this ![image](https://private-user-images.githubusercontent.com/49340378/301234218-88d2de41-1a25-4548-a0ef-4e9af1efd7b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTkwNjEsIm5iZiI6MTcwNjcxODc2MSwicGF0aCI6Ii80OTM0MDM3OC8zMDEyMzQyMTgtODhkMmRlNDEtMWEyNS00NTQ4LWEwZWYtNGU5YWYxZWZkN2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE2MzI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzBjZTA0NTk5YjIxNWE4Nzg0OWE1MzkwMzc4NjlkYWNiMTY1MTU5NTg0MTUyOTQ4NTBhMzIwOTE5NGVlODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FQndV2IJafZV37wA7pwbFwN07RV4Z-GaSwUAGayY8Wo)

What's the design of the icons in the berry/ingredient stats page? I have a vague memory of putting the shadowing class names to `<AnimatedCollapse/>` but not 100% sure

**Comment by wakashio** [comment]
Is this component correct?
The hierarchy is so deep that I still haven't figured out where AnimatedCollapse is used on the berry page.
https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/main/src/ui/berry/page/favoriteInfo.tsx


I'm completely hard-coding and ignoring lint, but I think I can fix the design this way.
https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/3fd136e158bd68d1add069f47c8056af59a464c8/src/ui/pokedex/tier/result/single/main.tsx#L71-L75

```
              <AnimatedCollapse key={key} show appear noFullWidth className={getFlexStyles('col', {noFullWidth: true, className: 'button-clickable-bg'})}>
                <FlexButton
                  direction="col"
                  className="items-center gap-1 p-2"
                  onClick={() => onPokemonClicked(pokemon)}
                >
```

![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/49340378/adb83a65-8946-40db-954e-80a1658fc29d)

**Comment by wakashio** [comment]
That's it for today.
I want to finish my `side work` on time and fix it tomorrow.

**Comment by RaenonX** [comment]
Seems like `button-*` class is on `<AnimatedCollapse>`, which wraps a `<FlexButton>` inside.
