### ISSUE TITLE
Team maker to avoid OOM

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/pokemon-sleep-ui#740]
https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/28d1da8a23eb58a9b29f90b1d8de65fae66ee32a/src/ui/team/maker/hook/generateComp.worker.ts#L5

`combineIterator()` exhausts every possibilities, therefore requiring a lot of memory.

Consider making combination generation separable so the team comp calculation can still run in parallel (i.e. not exhausting combinations all at once).

**Comment by RaenonX** [comment]
Check https://discord.com/channels/1138701819464392744/1181411222470537297/1216610261671350323 for continue-able impl

**Comment by jeancroy** [comment]
updated with some test. Added algorithms computing number of combinations as a bonus.

```js

import {describe, test, expect} from '@jest/globals';


describe('When generating combinations', ()=> {
  // The number of combinations without repeat is binomial coefficient.
  // https://en.wikipedia.org/wiki/Binomial_coefficient
  // Same as with all the P(at least k) that we used.
  //
  // Compute n! /( k! (n-k)!)
  // This implementation is much faster than computing the factorial
  // but can overflow during the multiplication.
  // (the factorials will also overflow, and are slow)

  const nCk = (n: number, k: number) => {
    if (k > n - k) k = n - k; // because C(n, r) == C(n, n - r)

    let ans: number = 1;
    for (let i = 1; i <= k; i++) {
      ans *= n - k + i;
      ans /= i;
    }

    return ans;
  };

  // Alternative that won't overflow but use a size n storage.
  const nCk_storage = (n: number, k: number) => {
    const arr = new Array(n);
    for (let i = 0; i < n; i++) arr[i] = 0;

    // this is the value of nCk(0, 0)
    arr[0] = 1;

    // Using nCk(n, k) = nCk(n - 1, k - 1) + nCk(n - 1, k)
    for (let i = 1; i <= n; i++) {
      for (let j = i; j > 0; j--) {
        arr[j] += arr[j - 1];
      }
    }

    return arr[k];
  };

  // What you currently use
  const getCombinationCount = (objects: number, sample: number): number => {
    return factorial(objects) / (factorial(sample) * factorial(objects - sample));
  };
  const factorial = (num: number) => {
    let value = 1;
    for (let i = 2; i <= num; i++) {
      value = value * i;
    }
    return value;
  };

  // Generator part

  const initial = (
    digits: number,
    alphabetSize: number,
  ): number[] | null => {
    if (digits > alphabetSize) {
      throw new Error(`Cant produce ${digits} distinct items from ${alphabetSize} symbols`);
    }
    const arr = new Array(digits);
    for (let i = 0; i < digits; i++) arr[i] = i;
    return arr;
  };

  const next = (
    current: number[],
    alphabetSize: number,
  ): number[] | null => {
    const digits = current.length;
    let lastSymbolForCursor = alphabetSize - 1;
    let cursor = digits - 1;
    const arr = current.slice(0, digits);

    // find the first digit that is not at its max value
    while (arr[cursor] >= lastSymbolForCursor) {
      if (cursor == 0) return null;
      arr[cursor] = lastSymbolForCursor;
      lastSymbolForCursor--;
      cursor--;
    }

    // increase that digit
    arr[cursor]++;

    // reset digits to the right to the lowest value allowed
    // while still maintaining sorted ascending order.
    let value = arr[cursor] + 1;
    for (let i = cursor + 1; i < digits; i++) {
      arr[i] = value;
      value++;
    }

    return arr;
  };

  const uniformRandomInt = (a:number, b:number) => {
    return a + ((b-a)*Math.random())|0;
  };

  // cheap way to bias toward the center
  const triangularRandomInt = (a:number, b:number) => {
    return (uniformRandomInt(a, b) + uniformRandomInt(a, b))>>1;
  };

  // randomised inputs, so we are not correct, just by accident
  const k = triangularRandomInt(1, 6); // k > 0
  const n = k + triangularRandomInt(0, 20); // n >= k

  const count1 = nCk(n, k);
  const count2 = nCk_storage(n, k);
  const count3 = getCombinationCount(n, k);


  describe(`when computing ${k} picks out of ${n} items`, () => {
    test('the different methods to compute number of combinations give the same answer', () => {
      expect(count1).toBe(count2);
      expect(count1).toBe(count3);
      expect(count2).toBe(count3);
    });

    test('the generator produce the correct number of results', () => {
      let state = initial(3, 5); // ABC ...CDE
      let generated = 0;

      while (true) {
        generated++;
        state = next(state!, 5);
        if (state == null) break;
        if (generated > 2 * count1) throw Error('Infinite loop?');
      }
    });
  });
});


```

**Comment by jeancroy** [comment]
The funny thing is this. nCk, the number of combinations is part of binomial.
The reason you can't have 2 decimal on the 25% luck is that you can't have 2 decimal on the number of combination.

**Comment by jeancroy** [comment]
Test suite is missing 2 test.

1) Within a generated combination all numbers are different. 
    (You can test they are sorted and not two consecutive equal)

2) Amongst all combinations there's no repeat.

I'm sure both will pass. But then, together with overall count, the test suite will be mathematically correct.

**Comment by jeancroy** [comment]
How I'd divide work between worker.
 There's k worker.
 First worker get first item, second worker get second ... 
 Then when they finish they can check their current offset +k.
 
 To do that one need to jump k items.
 Calling next() k time is safe. 
 Unless the last digit is a last symbol, the only work done is arr[cursor]++;
 When it is a last symbol the work is proportional to the carry size like 5678 goes into 6234.
 
 Even if instead you want to allocate say 100 item to worker a, 100 items to worker b etc, we need some jump() method.
 
 What I'd do is have a public next() and jump()  that make a copy then call/loop a private _next() that does the work in place.

**Comment by RaenonX** [comment]
> How I'd divide work between worker. There's k worker. First worker get first item, second worker get second ... Then when they finish they can check their current offset +k.
> 
> To do that one need to jump k items. Calling next() k time is safe. Unless the last digit is a last symbol, the only work done is arr[cursor]++; When it is a last symbol the work is proportional to the carry size like 5678 goes into 6234.
> 
> Even if instead you want to allocate say 100 item to worker a, 100 items to worker b etc, we need some jump() method.
> 
> What I'd do is have a public next() and jump() that make a copy then call/loop a private _next() that does the work in place.

Hmmm, since worker can't take class / object only, that means we'll need some sort of type that holds the states, and we manipulate that state in object?

**Comment by RaenonX** [comment]
> Test suite is missing 2 test.
> 
> 1. Within a generated combination all numbers are different.
>    (You can test they are sorted and not two consecutive equal)
> 2. Amongst all combinations there's no repeat.
> 
> I'm sure both will pass. But then, together with overall count, the test suite will be mathematically correct.

Done added related tests.

**Comment by RaenonX** [comment]
Likely need to think of how to jump the state to allow parallelism. Currently this allows single thread web worker but not multiplie.
